version: '3'

services:
  django:
    build:
      context: /backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  nextjs:
    build:
      context: /frontend
    ports:
      - "3000:3000"
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
