name: SonarQube Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Specify the Python version you are using

      - name: Install pip
        run: |
          python -m pip install --upgrade pip==23.2.1  # Replace with the pip version you want to use

      - name: Install dependencies for Django
        run: |
          pip install -r backend/requirements.txt

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies for Next.js
        working-directory: ./frontend
        run: npm install

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION_KEY: ${{ secrets.SONAR_ORGANIZATION_KEY }}
        # working-directory: ./frontend
        run: |
          npm install -g sonarqube-scanner
          sonar-scanner \
            -Dsonar.projectKey=LikithKumarDK_Django-NextJS \
            -Dsonar.sources=./ \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=$SONAR_ORGANIZATION_KEY \
            -Dsonar.login=$SONAR_TOKEN
